# Importing NumPy

In [2]:
import numpy as np

# Creating One-Diamentional Array

In [2]:
np1 = np.array([10,20,30])
print(np1)

## Checking variable type

In [4]:
print(type(np1))

<class 'numpy.ndarray'>


# Creating Two-Diamentional Array

In [5]:
np2 = np.array([[10,20,30], [10,20,30]])
print(np2)

## Checking variable type

In [7]:
type(np2)

numpy.ndarray

# np.zero(('row', 'column'))

## initilize an array with zeros 

to initilize array with only zeroes we can use 
np.zeros() method which accepts two parameters (row,columns) in number eg. we want to rows and two columns with all zero values we can use np.zeros(2,2) as followed

In [17]:
np3 = np.zeros((1,2))

In [18]:
np3

array([[0., 0.]])

In [14]:
np4 = np.zeros((10,10))

In [15]:
np4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
print(np4)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# np.full(('row', 'column'), num)

np.full() metod used to generate an 2D array with the specific number we will pass, it accept two parameters 1. diamention tuple and number we want in array eg.  if we want to create a array with 2 rows and 4 columns which will have only number 6 we can do it as followed

In [20]:
np5 = np.full((2,4),6)

In [21]:
print(np5)

[[6 6 6 6]
 [6 6 6 6]]


# np.arange('start', 'stop','increment')

np.arange() method is used to create an array with numbers within a range we will define, it accept two main and one optional parameter where par1 is start point, par2 is stop point and par3 is a values to be increased by eg. we want to create an array with numbers 1-10 we can do it as followed

In [23]:
np6= np.arange(1,10)

In [24]:
print(np6)

[1 2 3 4 5 6 7 8 9]


In [25]:
np6= np.arange(1,10,2)

In [26]:
print(np6)

[1 3 5 7 9]


# np.random.randint()

This array method is used to generate array with random numbers within a range we define, it accepts three parameters 'start', 'stop', and 'no_of_values' we want in our array, eg we want 10 numbers from 1-100 in our array we can do it as followed

In [35]:
np6 = np.random.randint(1,100,10)

In [36]:
print(np6)

[47 55 51 52 69 67 26 26  7 63]


# np.shape

np.shape method is used to know the shape(no of rows and columns) in an array using this we can also modify the shape of existing array eg. if we have array with 2 rows and 3 columns we can change it to either (2,3) || (1,6) || (6,1) etc.. , the no of element remains same only shape had been changed

In [37]:
np7 = np.array([[10,20,30], [40,50,60]])

In [38]:
print(np7)

[[10 20 30]
 [40 50 60]]


In [40]:
np7.shape

(2, 3)

In [46]:
np7.shape = (3,2)

In [47]:
print(np7)

[[10 20 30 40 50 60]]


# Array stacking vstack((ar1, ar2)), hstack((ar1, ar2)), column_stack((ar1, ar2))

When we have multiple arrays we can stack them as one using # vstack((ar1, ar2)), hstack((ar1, ar2)), column_stack((ar1, ar2)) methods it accept tuple as with arays we want to stack as parameter

In [49]:
ar1 = np.array([10,20,30])
ar2 = np.array([40,50,60])

In [52]:
print(ar1)
print('\n')
print(ar2)

[10 20 30]


[40 50 60]


## vstack((ar1, ar2))

vstack() will arange array in vertical manner as followed

In [55]:
ver_stacked = np.vstack((ar1, ar2))
print(ver_stacked)

[[10 20 30]
 [40 50 60]]


## hstack((ar1, ar2))

hstack() will arange array's in horizontal format as followed

In [56]:
hor_stacked = np.hstack((ar1, ar2))
print(hor_stacked)

[10 20 30 40 50 60]


## column_stack((ar1, ar2))

col_stack will arange array's by considering each array as a columns as followed

In [57]:
col_stacked = np.column_stack((ar1, ar2))
print(col_stacked)

[[10 40]
 [20 50]
 [30 60]]


# Numpy intersect and difference

we have np.intersect1d('ar1','ar2') and np.setdiff1d('ar1','ar2') methods, to see intersection and difference between two arrays

In [61]:
ar1 = np.array([10,20,30,40])
ar2 = np.array([30,40,50,60])

## np.setintersect1d('ar1', 'ar2') 

method is used to find intersection between two arrays, it wil find all the simillar values which are there in both arrays, it takes two parameters array1 and array2 as followed

In [62]:
intersect = np.intersect1d(ar1,ar2)
print(intersect)

[30 40]


## np.setdiff1d('ar1', 'ar2')

np.setdiff1d('ar1', 'ar2') method is used to find difference between two arrays, it wil find values which are there in the first array we passed but not in second array we pass in short it exclude the simillar values, it takes two parameters array1 and array2 as followed 

In [63]:
np.setdiff1d(ar1,ar2)

array([10, 20])

In [64]:
np.setdiff1d(ar2,ar1)

array([50, 60])

# Numpy Array Mathematics

## np.sum(('ar1', 'ar2'), axis = 0 || 1)

this method will return the summation of all the elements in both array we will passed to , it takes two main and one optional parameters which is two arrays we want to make summation of and axis , if we set axis to 0 like axis = 0 then it will return the summation column wise whereas if we use axis = 1 it will return summation row wise as followed

In [66]:
ar1 = np.array([10,20])
ar2 = np.array([30,40])

In [68]:
np.sum((ar1,ar2))

100

In [69]:
np.sum((ar1,ar2), axis = 0)

array([40, 60])

In [70]:
np.sum((ar1,ar2), axis = 1)

array([30, 70])

# Basic mathematics in NumpyArray

In [3]:
arr = np.array([10,20,30,40,50,60])
print(arr)

[10 20 30 40 50 60]


## Addition

In [4]:
arr = arr+1
print(arr)

[11 21 31 41 51 61]


## Substraction

In [7]:
arr = arr-1
print(arr)

[10 20 30 40 50 60]


## Multiplication

In [8]:
arr *=2
print(arr)

[ 20  40  60  80 100 120]


## Division

In [9]:
arr = arr/2
print(arr)

[10. 20. 30. 40. 50. 60.]


# NumPy Maths Functions

## Mean

In [10]:
arr_mean = np.mean(arr)
print(arr_mean)

35.0


## Standard Daviation

In [11]:
arr_std_dav = np.std(arr)
print(arr_std_dav)

17.07825127659933


## Median

In [12]:
arr_med = np.median(arr)
print(arr_med)

35.0


# Save NumPy Array

In [13]:
np.save('Study',arr)

# Load NumPy Array

In [17]:
arr2 = np.load("D:\\Programs\\Machine Learning\\Study\\Study.npy")
print(arr2)

[10. 20. 30. 40. 50. 60.]
